package fieldname

import "github.com/1Password/shell-plugins/sdk"

// Credential field names.
const (
	Token           = sdk.FieldName("Token")
	Key             = sdk.FieldName("Key")
	Username        = sdk.FieldName("Username")
	User            = sdk.FieldName("User")
	Password        = sdk.FieldName("Password")
	AuthToken       = sdk.FieldName("Auth Token")
	Credential      = sdk.FieldName("Credential")
	Credentials     = sdk.FieldName("Credentials")
	AccountSID      = sdk.FieldName("Account SID")
	AccountID       = sdk.FieldName("Account ID")
	Account         = sdk.FieldName("Account")
	AccessKeyID     = sdk.FieldName("Access Key ID")
	SecretAccessKey = sdk.FieldName("Secret Access Key")
	Secret          = sdk.FieldName("Secret")
	AppToken        = sdk.FieldName("App Token")
	AppKey          = sdk.FieldName("App Key")
	AppSecret       = sdk.FieldName("App Secret")
	APIKey          = sdk.FieldName("API Key")
	APISecret       = sdk.FieldName("API Secret")
	APIHost         = sdk.FieldName("API Host")
	PrivateKey      = sdk.FieldName("Private Key")
	Cert            = sdk.FieldName("Cert")
	Certificate     = sdk.FieldName("Certificate")
	Host            = sdk.FieldName("Host")
	HostAddress     = sdk.FieldName("Host Address")
	Port            = sdk.FieldName("Port")
	URL             = sdk.FieldName("URL")
	Website         = sdk.FieldName("Website")
	Database        = sdk.FieldName("Database")
	Address         = sdk.FieldName("Address")
	Namespace       = sdk.FieldName("Namespace")
	Region          = sdk.FieldName("Region")
	Organization    = sdk.FieldName("Organization")
	Mode            = sdk.FieldName("Mode")
	OneTimePassword = sdk.FieldName("One-Time Password")
)
