package fieldname

// Commonly used field names.
const (
	Token           = "Token"
	Key             = "Key"
	Username        = "Username"
	User            = "User"
	Password        = "Password"
	AuthToken       = "Auth Token"
	Credential      = "Credential"
	Credentials     = "Credentials"
	AccountSID      = "Account SID"
	AccountID       = "Account ID"
	Account         = "Account"
	AccessKeyID     = "Access Key ID"
	SecretAccessKey = "Secret Access Key"
	Secret          = "Secret"
	AppToken        = "App Token"
	AppKey          = "App Key"
	AppSecret       = "App Secret"
	APIKey          = "API Key"
	APISecret       = "API Secret"
	APIHost         = "API Host"
	PrivateKey      = "Private Key"
	Cert            = "Cert"
	Certificate     = "Certificate"
	Host            = "Host"
	HostAddress     = "Host Address"
	Port            = "Port"
	URL             = "URL"
	Website         = "Website"
	Database        = "Database"
	Address         = "Address"
	Namespace       = "Namespace"
	Region          = "Region"
	Organization    = "Organization"
	Mode            = "Mode"
	OneTimePassword = "One-Time Password"
)
