version: "2"
linters:
  default: none
  enable:
    # Defaults:
    - govet
    - ineffassign
    - unused
    # Extra:
    - asciicheck
    - bidichk
  disable:
    # Scott L: currently these produce errors that need to be fixed in a seprate PR
    - errcheck
    - depguard
    - staticcheck

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: math/rand
              desc: "please use the safer crypto/rand"

formatters:
  enable:
    - gofmt
    - goimports
