version: "2"
linters:
  default: none
  enable:
    # Defaults:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Extra:
    - asciicheck
    - bidichk
    - depguard

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: math/rand
              desc: "please use the safer crypto/rand"

formatters:
  enable:
    - gofmt
    - goimports
