name: Check Nix flake
on:
  pull_request:
    paths:
      - "**.nix"
      - flake.lock
  push:
    branches:
      - main
jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15
        with:
          use-flakehub: false
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@786422608c7bded2bbc9741ad9f91356842bf520 # v14
        with:
          fail-mode: true
          send-statistics: false
      - name: Run nix flake check
        run: nix flake check
