name: Check Nix flake
on:
  pull_request:
    paths:
      - "**.nix"
      - flake.lock
  push:
    branches:
      - main
jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
        with:
          use-flakehub: false
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@4b90f9fc724969ff153fe1803460917c84fe00a3 # v5
        with:
          fail-mode: true
          send-statistics: false
      - name: Run nix flake check
        run: nix flake check
